In [7]:
import pandas as pd
dataset = pd.read_csv('cardio_dataset.csv').values
#Load the dataset into a numpy array
print(dataset[:10],dataset.shape)

[[  2.   48.  236.   66.    0.    2.    0.    1.1]
 [  1.   48.  260.   51.    0.    2.    1.    7. ]
 [  1.   44.  187.   49.    1.    2.    0.    7. ]
 [  2.   42.  216.   57.    1.    2.    0.    0.4]
 [  2.   56.  156.   42.    0.    2.    0.    2.2]
 [  1.   44.  162.   57.    1.    2.    0.    3. ]
 [  1.   50.  244.   47.    0.    2.    0.    4.2]
 [  1.   48.  212.   30.    1.    2.    0.   17.4]
 [  2.   66.  202.   53.    0.    2.    1.   13.4]
 [  1.   63.  186.   46.    1.    2.    0.   17.3]] (6644, 8)


In [9]:
data = dataset[:,0:7]
target = dataset[:,7]

In [17]:
from sklearn.model_selection import train_test_split

train_data, test_data, train_target, test_target = train_test_split(data, target, test_size=0.2)

In [21]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(train_data, train_target)

LinearRegression()

In [23]:
predicted_target = model.predict(test_data)

In [25]:
from sklearn.metrics import r2_score

r2 = r2_score(test_target, predicted_target)
print("r2 score:", r2)

r2 score: 0.7407950601858226


In [26]:
#read about feature engineering and apply preprocessing to the dataset and try to improve the r2 score

In [28]:
import joblib

joblib.dump(model,'regression-model-heart-risk.sav')

['regression-model-heart-risk.sav']